import { ChangeEvent, useEffect, useRef, useState } from 'react';
import { getTemplate, getTemplates, type PostType } from './config/templateConfig';
import { createChatGptPrompt, type PromptRequestType } from './utils/chatgptPrompt';
import { render, type TextStyle } from './utils/canvas';
import './chatgpt.css';

type Values = { text1: string; text2: string; subtitle: string; tag1: string; tag2: string; label: string };
const initial: Values = { text1: '', text2: '', subtitle: '', tag1: '', tag2: '', label: '' };
const FONT_OPTIONS = [{ label: 'ゴシック（Noto Sans JP）', value: '"Noto Sans JP", "Hiragino Kaku Gothic ProN", "Yu Gothic", sans-serif' }, { label: 'ヒラギノ角ゴ', value: '"Hiragino Kaku Gothic ProN", "Noto Sans JP", sans-serif' }, { label: '游ゴシック', value: '"Yu Gothic", YuGothic, "Noto Sans JP", sans-serif' }, { label: '明朝', value: 'serif' }, { label: '標準 sans-serif', value: 'sans-serif' }];
const defaultStyle = (size: number): TextStyle => ({ size, family: FONT_OPTIONS[0].value, color: '#333333', weight: 700 });
const dateString = () => new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' }).split('-').join('');
const CHATGPT_CHAT_URL = 'https://chatgpt.com/c/6aaa81d5-feb0-83e8-81d2-cd22707f4501';
const WORDPRESS_DRAFT_URL = 'https://member-uemura-seitai.com/wp-admin/edit.php?post_status=draft&post_type=post';
const WORDPRESS_CHROME_URL = 'googlechromes://member-uemura-seitai.com/wp-admin/edit.php?post_status=draft&post_type=post';

async function makeSafeImage(file: File): Promise<HTMLImageElement> {
  let source: Blob = file;
  if (file.type.includes('heic') || /\.heic$/i.test(file.name)) { const module = await import('heic2any'); source = await module.default({ blob: file, toType: 'image/jpeg', quality: 0.9 }) as Blob; }
  const bitmap = await createImageBitmap(source); const max = 2400; const scale = Math.min(1, max / Math.max(bitmap.width, bitmap.height)); const c = document.createElement('canvas'); c.width = Math.round(bitmap.width * scale); c.height = Math.round(bitmap.height * scale); c.getContext('2d')!.drawImage(bitmap, 0, 0, c.width, c.height); bitmap.close();
  const img = new Image(); img.src = c.toDataURL('image/jpeg', 0.92); await img.decode(); return img;
}

export default function App() {
  const [type, setType] = useState<PostType | ''>(() => localStorage.getItem('rooms:type') as PostType || '');
  const [shop, setShop] = useState(() => localStorage.getItem('rooms:shop') || '');
  const [values, setValues] = useState<Values>(initial); const [text1Style, setText1Style] = useState<TextStyle>(() => defaultStyle(type === 'health' ? 72 : 44)); const [text2Style, setText2Style] = useState<TextStyle>(() => defaultStyle(62)); const [verticalOffset, setVerticalOffset] = useState(0); const [upload, setUpload] = useState<HTMLImageElement>(); const [uploadName, setUploadName] = useState(''); const [error, setError] = useState(''); const [advanced, setAdvanced] = useState(false); const [textSettings, setTextSettings] = useState(false); const [ready, setReady] = useState(false); const [generated, setGenerated] = useState(false); const [shareDone, setShareDone] = useState(false); const [sharing, setSharing] = useState(false);
  const [chatOpen, setChatOpen] = useState(false); const [requestType, setRequestType] = useState<PromptRequestType>('post'); const [additionalInstructions, setAdditionalInstructions] = useState(''); const [chatPrompt, setChatPrompt] = useState(''); const [chatStatus, setChatStatus] = useState('');
  const canvasRef = useRef<HTMLCanvasElement>(null); const template = type && shop ? getTemplate(type, shop) : undefined;
  useEffect(() => { if (type) localStorage.setItem('rooms:type', type); }, [type]); useEffect(() => { if (shop) localStorage.setItem('rooms:shop', shop); }, [shop]);
  useEffect(() => { if (!template || !canvasRef.current) return; setReady(false); render(canvasRef.current, template, { ...values, text1Style, text2Style, verticalOffset, uploaded: upload }).then(() => setReady(true)).catch(() => { setReady(false); setError('テンプレート画像を読み込めませんでした'); }); }, [template, values, text1Style, text2Style, verticalOffset, upload]);
  useEffect(() => { setGenerated(false); setShareDone(false); }, [template, values, upload]);
  const selectType = (next: PostType) => { setType(next); if (!getTemplates(next).some((item) => item.id === shop)) setShop(''); setText1Style((style) => ({ ...style, size: next === 'notice' ? 44 : 72 })); setError(''); };
  const imageSelected = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setError(''); try { setUpload(await makeSafeImage(file)); setUploadName(file.name); } catch { setError('この画像形式は読み込めません。JPEGまたはPNGでお試しください'); event.target.value = ''; } };
  const generate = () => { if (!type) return setError('投稿タイプを選択してください'); if (!shop) return setError('加盟店を選択してください'); if (!(values.text1.trim() || values.text2.trim())) return setError(type === 'notice' ? 'テキスト1またはテキスト2を入力してください' : 'タイトルを入力してください'); if (!ready) return setError('テンプレート画像を読み込めませんでした'); setError(''); setGenerated(true); setShareDone(false); canvasRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' }); };
  const fileName = () => `ROOMs_${type === 'notice' ? 'お知らせ投稿' : '健康情報'}_${template?.shop}_${dateString()}.png`;
  const pngFile = async () => new File([await new Promise<Blob>((resolve) => canvasRef.current!.toBlob((blob) => resolve(blob!), 'image/png'))], fileName(), { type: 'image/png' });
  const download = async () => { const file = await pngFile(); const a = document.createElement('a'); a.href = URL.createObjectURL(file); a.download = file.name; a.click(); URL.revokeObjectURL(a.href); };
  const share = async () => { setSharing(true); try { const file = await pngFile(); await navigator.share({ title: 'ROOMs吹田 アイキャッチ画像', files: [file] }); } catch { /* The user may cancel the native share sheet; they can still continue deliberately. */ } finally { setSharing(false); setShareDone(true); } };
  const makeChatPrompt = () => { const textStyleSummary = `テキスト1は${text1Style.weight >= 700 ? '太字' : '標準'}・${text1Style.color}${type === 'notice' ? `、テキスト2は${text2Style.weight >= 700 ? '太字' : '標準'}・${text2Style.color}` : ''}`; setChatPrompt(createChatGptPrompt({ requestType, postType: type, shopId: template?.id || shop, shopName: template?.shop || '', ...values, uploadName, additionalInstructions, textStyleSummary })); setChatStatus('プロンプトを作成しました。'); };
  const copyChatPrompt = async () => { if (!chatPrompt) return; try { await navigator.clipboard.writeText(chatPrompt); setChatStatus('プロンプトをコピーしました。'); } catch { const area = document.querySelector<HTMLTextAreaElement>('#chatgpt-prompt'); area?.select(); document.execCommand('copy'); setChatStatus('プロンプトをコピーしました。'); } };
  const openWordPressDraft = () => { const isIOS = /iPad|iPhone|iPod/.test(navigator.userAgent) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1); if (!isIOS) { window.location.href = WORDPRESS_DRAFT_URL; return; } let fallbackTimer: number; const cancelFallback = () => { if (document.visibilityState !== 'visible') { window.clearTimeout(fallbackTimer); document.removeEventListener('visibilitychange', cancelFallback); } }; document.addEventListener('visibilitychange', cancelFallback); fallbackTimer = window.setTimeout(() => { document.removeEventListener('visibilitychange', cancelFallback); window.location.href = WORDPRESS_DRAFT_URL; }, 1200); window.location.href = WORDPRESS_CHROME_URL; };
  const showShare = typeof navigator !== 'undefined' && !!navigator.share && (!navigator.canShare || navigator.canShare({ files: [new File([], 'image.png', { type: 'image/png' })] }));
  const needsLabel = template?.type === 'health' && !!template.labelBox;
  const styleControls = (name: string, style: TextStyle, setStyle: (style: TextStyle) => void) => <fieldset className="text-style"><legend>{name}</legend><label>文字サイズ <output>{style.size}px</output><input type="range" min="24" max="90" value={style.size} onChange={(e) => setStyle({ ...style, size: Number(e.target.value) })} /></label><label>フォント<select value={style.family} onChange={(e) => setStyle({ ...style, family: e.target.value })}>{FONT_OPTIONS.map((font) => <option value={font.value} key={font.label}>{font.label}</option>)}</select></label><label>文字色<input className="color" type="color" value={style.color} onChange={(e) => setStyle({ ...style, color: e.target.value })} /></label><label>文字の太さ<select value={style.weight} onChange={(e) => setStyle({ ...style, weight: Number(e.target.value) as TextStyle['weight'] })}><option value="400">普通</option><option value="500">Medium</option><option value="700">太字</option></select></label></fieldset>;
  return <main><header><h1>ROOMs吹田 アイキャッチ作成</h1><p>画像は端末内だけで処理されます。</p></header>
    <section className="card"><h2><span>1</span> 投稿タイプ</h2><div className="choices two"><button className={type === 'notice' ? 'selected' : ''} onClick={() => selectType('notice')}>お知らせ投稿</button><button className={type === 'health' ? 'selected' : ''} onClick={() => selectType('health')}>健康情報</button></div></section>
    <section className="card"><h2><span>2</span> 加盟店</h2>{type ? <div className="choices shops">{getTemplates(type).map((item) => <button key={item.id} className={shop === item.id ? 'selected' : ''} onClick={() => { setShop(item.id); setError(''); }}>{item.shop}</button>)}</div> : <p className="hint">先に投稿タイプを選択してください。</p>}</section>
    <section className="card"><h2><span>3</span> {type === 'health' ? 'タイトル' : 'テキスト1'}</h2><textarea value={values.text1} onChange={(e) => setValues({ ...values, text1: e.target.value })} placeholder={type === 'health' ? '例：高血圧と\n自律神経の関係' : '例：商品ポイント'} rows={3} /></section>
    {type !== 'health' && <section className="card"><h2><span>4</span> テキスト2</h2><textarea value={values.text2} onChange={(e) => setValues({ ...values, text2: e.target.value })} placeholder={'例：カードが\nできました'} rows={3} /></section>}
    {type && <section className="card"><button className="details" onClick={() => setTextSettings(!textSettings)} aria-expanded={textSettings}>文字設定を開く <b>{textSettings ? '−' : '+'}</b></button>{textSettings && <div className="advanced text-settings">{styleControls(type === 'health' ? 'タイトル' : 'テキスト1', text1Style, setText1Style)}{type === 'notice' && styleControls('テキスト2', text2Style, setText2Style)}<label className="offset">上下位置 <output>{verticalOffset > 0 ? '+' : ''}{verticalOffset}px</output><input type="range" min="-50" max="50" value={verticalOffset} onChange={(e) => setVerticalOffset(Number(e.target.value))} /></label></div>}</section>}
    <section className="card"><h2><span>{type === 'health' ? '4' : '5'}</span> 画像</h2><p className="hint">{type === 'health' ? '健康情報では任意です。' : '投稿画像を1枚選択してください。'}</p><label className="upload"><input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={imageSelected} />画像を選択</label>{uploadName && <p className="file">選択中：{uploadName}</p>}</section>
    {type === 'health' && <section className="card"><button className="details" onClick={() => setAdvanced(!advanced)} aria-expanded={advanced}>詳細設定（任意） <b>{advanced ? '−' : '+'}</b></button>{advanced && <div className="advanced"><label>サブタイトル<input value={values.subtitle} onChange={(e) => setValues({ ...values, subtitle: e.target.value })} /></label><label>ハッシュタグ1<input value={values.tag1} onChange={(e) => setValues({ ...values, tag1: e.target.value })} /></label><label>ハッシュタグ2<input value={values.tag2} onChange={(e) => setValues({ ...values, tag2: e.target.value })} /></label>{needsLabel && <label>上部ラベル<input value={values.label} onChange={(e) => setValues({ ...values, label: e.target.value })} /></label>}</div>}</section>}
    <section className="card chatgpt-card"><button className="details" onClick={() => setChatOpen(!chatOpen)} aria-expanded={chatOpen}>ChatGPT連携 <b>{chatOpen ? '−' : '+'}</b></button>{chatOpen && <div className="advanced chatgpt-content"><fieldset className="chat-request-type"><legend>依頼タイプ</legend><div className="choices two"><button className={requestType === 'post' ? 'selected' : ''} onClick={() => setRequestType('post')}>投稿文作成用</button><button className={requestType === 'image' ? 'selected' : ''} onClick={() => setRequestType('image')}>画像生成用</button></div></fieldset><label>追加の指示<textarea value={additionalInstructions} onChange={(e) => setAdditionalInstructions(e.target.value)} placeholder="例：短めにまとめてください" rows={3} /></label><button className="chat-generate" onClick={makeChatPrompt}>{requestType === 'post' ? '投稿文作成用プロンプトを作成' : '画像生成用プロンプトを作成'}</button>{chatPrompt && <><label>生成されたプロンプト<textarea id="chatgpt-prompt" value={chatPrompt} readOnly rows={14} /></label><button onClick={copyChatPrompt}>コピー</button></>}<a className="chat-open" href={CHATGPT_CHAT_URL} target="_blank" rel="noopener noreferrer">{requestType === 'post' ? 'chatGPTで投稿文を作成' : 'chatGPTで画像を作成'}</a>{chatStatus && <p className="chat-status" role="status">{chatStatus}</p>}</div>}</section>
    <section className="card preview-card"><h2>プレビュー</h2>{template ? <canvas ref={canvasRef} aria-label="完成イメージのプレビュー" /> : <div className="empty">投稿タイプと加盟店を選ぶと表示されます</div>}</section>
    {error && <p className="error" role="alert">{error}</p>}<button className="create" onClick={generate}>画像を作成</button>{generated && <section className="exports" aria-label="保存と投稿"><h2>完成しました</h2>{showShare ? <><button className="photo-save" onClick={share} disabled={sharing}>{sharing ? '共有画面を開いています…' : '写真アプリに保存'}</button><p className="save-guide">共有画面で「画像を保存」を選んでください。</p></> : <p className="save-guide">このブラウザでは写真アプリへの共有に対応していません。下のボタンでファイルとして保存してください。</p>}{shareDone && <div className="wordpress-step"><p>写真への保存は完了しましたか？</p><button className="wordpress" onClick={openWordPressDraft}>WordPressの下書き投稿へ進む</button></div>}<button className="file-save" onClick={download}>ファイルとして保存</button></section>}
    <footer>画像はブラウザ内で処理され、外部サーバーには送信されません。</footer>
  </main>;
}
